monitoring:
  check_interval_hours: 24
  retention_days: 90
  trend_analysis_days: 30
notifications:
  email_recipients:
  - ''
  slack_webhook: null
  teams_webhook: null
pipeline_integration:
  auto_remediation: false
  create_github_issue: true
  fail_on_critical: true
  fail_on_warning: false
thresholds:
- comparison: greater_than
  critical_threshold: 60.0
  enabled: true
  metric_name: average_risk_score
  warning_threshold: 40.0
- comparison: greater_than
  critical_threshold: 3.0
  enabled: true
  metric_name: critical_count
  warning_threshold: 1.0
- comparison: greater_than
  critical_threshold: 10.0
  enabled: true
  metric_name: high_count
  warning_threshold: 5.0
